jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: ${{ runner.os != 'Windows' }}
      name: Make gradle wrapper executable
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Build the mod
      run: ./gradlew build
    - continue-on-error: true
      if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
      name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: 'build/libs/

          forge/build/libs/'
    strategy:
      matrix:
        java:
        - 17
        os:
        - ubuntu-22.04
        - windows-2022
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
