jobs:
  sync:
    name: Git Repo Sync
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-token: ${{ secrets.TARGET_TOKEN }}
        target-url: ${{ secrets.TARGET_URL }}
        target-username: ${{ secrets.TARGET_USERNAME }}
name: Gitlab Sync
on:
  repository_dispatch:
    types: trigger-ga___gitlabsync.yml
